spring.application.name=visitor-management
server.port=8080

# Firebase Configuration
firebase.config.path=classpath:serviceAccountKey.json
firebase.database.url=https://visitor-management-6f40f-default-rtdb.firebaseio.com
